/**
 * CivicSense AI — Centralized Category Configuration
 * Used across all pages for consistent colors, icons, and map pin colors.
 */

export const CATEGORIES = {
  "Road Damage": {
    color:      "text-red-400",
    bg:         "bg-red-900/30",
    border:     "border-red-700",
    solidBg:    "bg-red-500",
    pin:        "#ef4444",
    glowColor:  "rgba(239,68,68,0.4)",
    icon:       "🛣️",
    label:      "Road Damage",
    shortLabel: "Roads",
    desc:       "Potholes, cracks, road collapse",
  },
  "Garbage": {
    color:      "text-amber-400",
    bg:         "bg-amber-900/30",
    border:     "border-amber-700",
    solidBg:    "bg-amber-500",
    pin:        "#f59e0b",
    glowColor:  "rgba(245,158,11,0.4)",
    icon:       "🗑️",
    label:      "Garbage",
    shortLabel: "Garbage",
    desc:       "Illegal dumps, overflow bins",
  },
  "Water Leak": {
    color:      "text-blue-400",
    bg:         "bg-blue-900/30",
    border:     "border-blue-700",
    solidBg:    "bg-blue-500",
    pin:        "#3b82f6",
    glowColor:  "rgba(59,130,246,0.4)",
    icon:       "💧",
    label:      "Water Leak",
    shortLabel: "Water",
    desc:       "Pipe bursts, waterlogging",
  },
  "Broken Infrastructure": {
    color:      "text-orange-400",
    bg:         "bg-orange-900/30",
    border:     "border-orange-700",
    solidBg:    "bg-orange-500",
    pin:        "#f97316",
    glowColor:  "rgba(249,115,22,0.4)",
    icon:       "⚡",
    label:      "Broken Infrastructure",
    shortLabel: "Infra",
    desc:       "Streetlights, footpaths, signs",
  },
  "Fallen Trees & Debris": {
    color:      "text-emerald-400",
    bg:         "bg-emerald-900/30",
    border:     "border-emerald-700",
    solidBg:    "bg-emerald-500",
    pin:        "#10b981",
    glowColor:  "rgba(16,185,129,0.4)",
    icon:       "🌳",
    label:      "Fallen Trees & Debris",
    shortLabel: "Debris",
    desc:       "Storm debris, blocked paths",
  },
  "Graffiti / Vandalism": {
    color:      "text-purple-400",
    bg:         "bg-purple-900/30",
    border:     "border-purple-700",
    solidBg:    "bg-purple-500",
    pin:        "#a855f7",
    glowColor:  "rgba(168,85,247,0.4)",
    icon:       "🎨",
    label:      "Graffiti / Vandalism",
    shortLabel: "Graffiti",
    desc:       "Defaced property, broken windows",
  },
  "Traffic Hazard": {
    color:      "text-yellow-400",
    bg:         "bg-yellow-900/30",
    border:     "border-yellow-700",
    solidBg:    "bg-yellow-500",
    pin:        "#eab308",
    glowColor:  "rgba(234,179,8,0.4)",
    icon:       "🛑",
    label:      "Traffic Hazard",
    shortLabel: "Traffic",
    desc:       "Broken signals, missing signs",
  },
  "Street Lighting": {
    color:      "text-indigo-400",
    bg:         "bg-indigo-900/30",
    border:     "border-indigo-700",
    solidBg:    "bg-indigo-500",
    pin:        "#6366f1",
    glowColor:  "rgba(99,102,241,0.4)",
    icon:       "💡",
    label:      "Street Lighting",
    shortLabel: "Lighting",
    desc:       "Burnt out lights, dark alleys",
  },
  "Abandoned Vehicle": {
    color:      "text-slate-400",
    bg:         "bg-slate-800/50",
    border:     "border-slate-600",
    solidBg:    "bg-slate-500",
    pin:        "#64748b",
    glowColor:  "rgba(100,116,139,0.4)",
    icon:       "🚗",
    label:      "Abandoned Vehicle",
    shortLabel: "Vehicle",
    desc:       "Junk cars, blocked driveways",
  },
  "No Issue Found": {
    color:      "text-green-400",
    bg:         "bg-green-900/30",
    border:     "border-green-700",
    solidBg:    "bg-green-500",
    pin:        "#22c55e",
    glowColor:  "rgba(34,197,94,0.4)",
    icon:       "✅",
    label:      "No Issue Found",
    shortLabel: "None",
    desc:       "Image does not show a civic issue",
  },
};

export const DEFAULT_CATEGORY = {
  color:      "text-gray-400",
  bg:         "bg-gray-800/40",
  border:     "border-gray-700",
  solidBg:    "bg-gray-600",
  pin:        "#64748b",
  glowColor:  "rgba(100,116,139,0.3)",
  icon:       "❓",
  label:      "Unknown",
  shortLabel: "Unknown",
  desc:       "Unknown issue type",
};

/** Get category style object, falling back to DEFAULT_CATEGORY */
export const getCategoryStyle = (name) => CATEGORIES[name] || DEFAULT_CATEGORY;

/** Ordered list for rendering category filter bars */
export const CATEGORY_KEYS = [
  "Road Damage",
  "Garbage",
  "Water Leak",
  "Broken Infrastructure",
  "Fallen Trees & Debris",
  "Graffiti / Vandalism",
  "Traffic Hazard",
  "Street Lighting",
  "Abandoned Vehicle",
];
